project 'AFNetWorkTest.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#platform :ios, '7.0'
target 'AFNetWorkTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AFNetWorkTest
  
  pod "AFNetworking", "~> 2.0"
  pod 'SDWebImage', '~> 4.0'

end
